### ISSUE TITLE
Ignore terminals are ignored in regexes

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#103]
Might be a duplicate issue; whitespace literals are completely ignored in regexes. Workaround: escape spaces. Long-term, a better solution?

**Comment by tedinski** [comment]
Not really a duplicate issue. #37 is an enhancement idea that would fix this bug though.

**Comment by krame505** [comment]
So it appears that we are actually taking advantage of this in a few places to make complicated regexes more readable.  For example in ableC:
```
terminal FloatConstant_t /
	(((([0-9]+[\.])|         -- end with do
	  ([0-9]*[\.][0-9]+))    -- has dot
	 ([Ee][\+\-]?[0-9]+)?)|  -- optional exponent
	 ([0-9]+[Ee][\+\-]?[0-9]+)) -- No dot, mandatory exponent
	/ lexer classes {NumericLiteral};
```
If we want to maintain this behavior, we would need to redefine all of Silver's ignore terminals inside the `silver:definition:regex` grammar (which I have done temporarily to make things build) - probably not something we want since we are trying to treat the regex grammar as a library of sorts.  

So I'll probably end up fixing this so that whitespace and comments in a regex are handled as literals and change the ableC regexes, unless anyone has any different thoughts here.

**Comment by ericvanwyk** [comment]
In principle, there is no problem with a regex library/language having its own definitions of comments and whitespace.  But this is non-standard behavior - so I think it is OK to not have whiltespace or comments inside of regexs.
