### ISSUE TITLE
Flow type specifications

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#153]
Hi all, give syntax suggestions.

I'm adding the ability to declare flow types. So far I've got this idea:

```
flowtype Expr : forward {context, env}, errors {env}, pp {};
```

Now, there will also be convenience extensions, I think. If I get around to that, too:

```
nonterminal Expr with pp {}, errors {env}, forward {env};
```

but I'm mostly concerned about the standalone syntax, since it seems different than everything else.

Maybe I should add it as part of attribute occurrence declarations?

```
attribute errors occurs on Expr with {env};
```

But actually, that might just be another convenience extension feature. We still need to specify for forwards, after all, which isn't an occurrence.

Also, I'd like this to eventually be able to specify reference sets, too. Thoughts on that syntax?

```
flowtype Env : decorate {};
```

Maybe?

**Comment by tedinski** [comment]
Well. The colon is out, since that's the grammar path separator. And `with` is used by collections, so that idea is nixed for the convenience extension.

Right now

```
flowtype Expr = forward {context, env}, errors {env}, pp {};
```

**Comment by ericvanwyk** [comment]
I'm glad you're moving forward on this.

What about
  flowtype Expr (error) = {env};
or
  flowtype error on Expr = {env} ;
Your thesis treats this as function-looking kinds of things.

We might like two kinds of convenience extensions.
One centered on the attribute:
 flowtype error on Expr = {env}, on Stmt = {env}, on Decl = {env};
or even
 flowtype error on Expr, Stmt, Decl = {env};

but also one that is centered on a nonterminal, like what you've done
already
flowtype Expr is error = {env},  host = { ...}, forward = { ..} ;

**Comment by tedinski** [comment]
After sleeping on it, I don't like the convenience extensions I proposed, I think they make things too noisy. Maybe flowtype should be separate.

Also I like the idea of the two different methods you propose Eric, but I want to go another step further.

```
flowtype Expr = errors {env}, forward {};

flowtype errors {env} on Expr, Decl, Stmt;
```

The common case (so common I don't know of an exception off the top of my head) is for the flow type to be the same for the same attribute, so I don't want to repeat it for each nonterminal.

I think the real convenience extension would be to be able to attached a flow type to a synthesized attribute. I have no real proposal for syntax with this, but maybe:

```
synthesized attribute pp :: Document;

flowtype pp {};

nonterminal Expr with pp; -- automatically gets its flow type set to the default {} unless otherwise specified?
```

I don't think I'll get around to implementing this, though.

**Comment by krame505** [comment]
Hmm.  I was just going to say that I liked having the flow type declarations as part of the 'occurs on' or 'with' list in an attribute or nonterminal declaration.  Flow type declarations should always be at a place where an attribute or nonterminal is being declared, correct?  I wonder if we really should have this as a seperate declaration in the first place.  

Using '=' in defining flow types doesn't quite feel right, since you aren't defining a new item.  I guess this could be a point of confusion for newer users, that 'flowtype Expr = ...' and 'type Foo = ...' seem kinda-sorta similar but are really totally different.  How about using the type operator?  I guess this is closer to what you proposed originally:
```
flowtype Expr :: errors {env}, forward {};
```

**Comment by tedinski** [comment]
I agree they're logically related, but I think it clutters the syntax too much. And, as I observed with the possible convenience extension, the place we're probably much more likely want to specify a flow type is with the attribute itself, normally.

I thought about `=` `::` `::=` `:=` and such. I think `::` and `=` are both kinda equally "wrong" but that maybe `=` has more precedent. Haskell `data` declaration, for example.

I thought about maybe `with` but idk, the equals seems just fine to me.

**Comment by krame505** [comment]
Hmm.  I think I do actually like `with` more, that has a nice symmetry with a nonterminal declaration.  That avoids any confusion that you might be declaring something new.

**Comment by ericvanwyk** [comment]
Does it make sense to allow "attr {i1, i2}" in some/many declarations where
we now write just "attr" ?

attribute attr {i1, i2} occurs on NT;
nonterminal NT with attr{i1, i2};

attribute attr {i1, i2} :: T occurs on NT1, NT2;   - here i1, i2 apply to
all, or are viewed as defaults.

attribute attr {i1, i2} :: T occurs on NT1, NT2 {i1, i2, i3} ; - here it is
different for NT2, but I don't really like this syntax.

But this should all be convenience stuff.

flowtype attr {i1, i2} on NT1, NT2, NT3;  - this would mirror the above

flowtype NT with attr{i1, i2}, attt2{i3, i4}; --   or = instead of with.

If we anticipate using the convenience syntax more often, then I'd make
that look nice and then use that of influence how the less commonly used
'flowtype' syntax is used.

**Comment by krame505** [comment]
That is pretty much exactly what I was thinking.  
Providing a default for an attribute would need to be more than just convenience syntax, though.

**Comment by krame505** [comment]
Question: We infer flow types on local and production attributes, right?  If so, should we have custom syntax to specify flow types on these as well?

**Comment by tedinski** [comment]
Yeah, maybe collections should. I didn't run into needing it yet.
