### ISSUE TITLE
'occurs on' is more restricted in annotations than in attributes.

### ISSUE THREAD

**Issue by 200sc** [melt-umn/silver#195]
`attribute x occurs on Expr, Root;` is valid silver, but `annotation y occurs on Expr, Root;` is not. 

Writing the annotation line above will result in an unexpected token error at the character before the comma.

**Comment by krame505** [comment]
The reason that we don't support this is that it doesn't make sense because of what annotations are - remember that an annotation is essentially an extra hidden child of every production, that is provided by a named argument instead of positionally.  
Now think about what would happen if you tried to make an annotation occur on a nonterminal that already exists in a different grammar.  The declarations in the original grammar wouldn't be able to see the annotation, and so any productions called there would be missing the annotation.  This means that the annotation is really part of the nonterminal itself, not something that can be added on later.  
Thus, annotations really only make sense to simplify cases where every production on a nonterminal have the same child, and we want to be able to access this with dot-notation.  Pretty much the only use case we have found so far is location, but I am interested to hear if you have found others.  
Also, as a side-note, we originally considered intentionally making annotation syntax much more different than attribute syntax to avoid this sort of confusion...

**Comment by krame505** [comment]
OK, I think I may have misunderstood the issue you are raising here- I thought you meant that we didn't have `occurs on` syntax for annotations and wanted to add it, but after looking at the source we actually do have `occurs on` syntax, but just not the convenience syntax.  I am actually confused now why we have annotation `occurs on` syntax in the first place- @tedinski can you comment on this?

**Comment by tedinski** [comment]
Is there a use case? That's my only concern.

Annotations have a few rough edges because we've only ever implemented exactly what we needed as we needed it. In this case, though, annotation instances have to be exported by the nonterminal declaration, and Silver style preferences recommend using `nonterminal with` syntax whenever possible.

So we'd want some sort of use-case where you want the annotation separate from the nonterminal declarations but still in the host language. I can't think of one.

**Comment by 200sc** [comment]
I ran into this when coding what might be generated for origin tracking. Given that it's generated, the longer method of a list of single `occurs on` statements works too, but it was unintuitive that annotations and attributes had the same keywords for these statements but different syntax for those keywords.

**Comment by krame505** [comment]
Yeah, I guess that generating `occurs on` declarations within a host grammar is probably a valid use case, and if we have `occurs on` for annotations, then there is no reason not to have the convenience syntax.  

Also, I just did some testing and apparently we aren't actually raising any sort of error for an annotation instance that isn't exported by the nonterminal, we are apparently treating these the same as attributes.  I'm not 100% sure what is supposed to be going on here, so I'll let @tedinski comment before opening an issue.

**Comment by ericvanwyk** [comment]
@krame505 - what exactly did you test?  Adding an annotation to a NT in a grammar that imports the one declaring the NT?  We should make sure that the appropriate errors are generated.

Even if using `occurs on` is not preferred style, the current status of generating a syntax error for what appears to be reasonable syntax is not very nice.

**Comment by krame505** [comment]
Yes, that is correct- adding an annotation to a nonterminal imported from another grammar currently gives no errors.  
With Ted's approval, merging #196 should fix the syntax errors.

**Comment by ericvanwyk** [comment]
In that case we should open an issue to track this bug.

Merging seems good to me.

**Comment by tedinski** [comment]
Generated code seems like a reasonable use-case.

Yeah, if it's not raising errors for out-of-grammar annotation occurrences, that's a bug.
