### ISSUE TITLE
Add an option to run Silver without generating translation

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#248]
Building a jar isn't needed when we are running modular analyses, so being able to disable this phase would significantly speed up building extensions on Jenkins.  We may still want to write interface files though maybe?  

One possible idea: For now, simply add a flag to disable generating the buildfile.  The `silver` script would then check if `build.xml` exists before running `ant`.

**Comment by tedinski** [comment]
This would also be useful for melt-website and generated documentation.

**Comment by tedinski** [comment]
I'm modifying the existing `--dont-translate` option to be fit for this purpose.

I'm planning on making this:

1. NOT translate java, as the flag already does, just not currently in a useful way.
2. NOT compile parsers! I'm not 100% certain about this choice: in some respects, compiling parsers is part of checking if things are ok, not translation? But I think in all cases where we're actually going to use this flag, skipping parsers is actually desired because they've already been checked. Unless all parser compilation would be skipped anyway?
3. DO perform Copper MDA.
4. NOT building a jar file.

So this should make it possible to use for all of:

1. Doing *just* the MWDA. Error checking happens as usual.
2. Doing *just* the MDA, because that's not suppressed.
3. Building documentation.

**Comment by krame505** [comment]
SGTM.  Just to check, though, would we still be generating interface files when this flag is given?

**Comment by tedinski** [comment]
No interface files. Don't think we want to. It'd put `generated` into a corrupted state, thinking grammars have been recompiled since they were changed, but haven't actually been...

**Comment by krame505** [comment]
Ah, makes sense.  I guess it doesn't really impact performance though since we usually run modular analyses with `--clean` anyway.
