### ISSUE TITLE
Better autocopy implementation

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#280]
## The basic problem

Autocopy equations can't be statically generated. This simplest scenario to see where statically generating autocopy equations would fail is the following:

* Host language.
* Extension 1 with new autocopy attribute.
* Extension 2 with new forwarding production.

There is no (modular) place to generate the autocopy equations for the children of that production. This example is slightly contrived, however, because the MWDA would also mean the autocopy attribute would never be _demanded_ from that production's children!

But we could always add a forth piece:

* Extension 3 using 1&2, aspects that production, and causes demands for that autocopy attribute on the children.
* (Likewise, more extensions could do the same thing.)

> _Edit: Complete aside: Lucas points out that this makes autocopy able to do ever so slightly more than we would be able to do with just ordinary inherited attributes under the MWDA. Ext3 with normal inherited attributes would be disallowed, because the inherited equations do not exist, and adding them in that extension would be "orphaned." But autocopy doesn't mind adding them, even if orphaned, because we're in the seemingly unique situation that the missing equation could only take one form: autocopying._

## The problem with dynamic generation

Silver startup time is slow, and a part of the reason why is that we iterate over every single production looking for missing autocopy equations, before we start running any Silver code at all. We want to speed this up.

Bonus points for also removing unwanted information we currently must jam into the runtime. For instance, we currently generate a list of types of children specifically for autocopy startup to look at to determine whether to insert equations. So getting rid of this dynamic generation could also allow us to remove filling this information in at startup. Synergy!

## There is an extremely common case

Almost always, autocopy equations can be statically generated! Most autocopy attributes are in the host language, and so could be statically generated for every production (host or extension).

However, not all are. A good canonical example is `substituted` in AbleC, which uses a `substitutions` autocopy attribute. (Although this is an `option` from the host, that still doesn't mean we can statically generate equations for this attribute, since if the grammar is never included, this attribute doesn't exist!)

## Potential solutions

1. Dynamic generation at startup, as we do now.
2. Dynamic generation, but at runtime when we discover missing equations.
3. Hybrid: statically generate the common case, dynamically generate at runtime for missing equations.
    * Possible downside: we'd still need sufficient information around at runtime to be able to dynamically generate them. So we wouldn't get that synergistic effect.
4. Restrictions: autocopy could be host language only.
    * Serious problem for things like `substituted`
5. Static re-generation: Statically generate host language case, but add on a "transitive dependencies" static generator that fills in all potentially non-existant autocopy equations. This could cause "duplicate equations" to be filled in, but that's hardly an issue for autocopy.
    * Drawback: requires all grammars to pass MWDA.

## Current thoughts

We should see if we can make the Hybrid3 approach work well. Perhaps we can reduce the amount of information the runtime would need to dynamically generate missing equations to something trivial.

The basic problem at runtime generation is that a `DecoratedNode` gets demands for `inherited(X)` where `X` is the integer index of an inherited attribute. It's missing. So we have to figure out that `X` means attribute `A`, that `A` is autocopy, then look at the parent nonterminal, see if it has `A` and if so at which index `Y`, then fill in the Lazy that just accesses `Y`.

(Neat trick: because we just pass the same array of Lazys around when decorating children, we can mutate that array once, and it'll update everywhere it's been used.)

On possible solution here is to store just two arrays on each nonterminal: array of autocopy attribute names, array of autocopy attribute indexes. Then a `DecoratedNode` with a missing equation could start by seeing if it's index is in its own nonterminal's array, then it could look for that same string in its parent's nonterminal's array, then get the index. This would be a pretty small amount of information, and has the advantage that it's per-nonterminal, instead of per-production, like a lot of the metadata we have to generate right now.

**Comment by krame505** [comment]
@ericvanwyk This issue explains the issues with / advantages of autocopy pretty thoroughly.  A few additional comments on this:
* The case where autocopy is *slightly* more powerful than regular inherited attributes by being able to fill in the otherwise-orphaned equations is ...not really a huge deal.  I can't actually think of a case when this has saved the day in practice, since extensions don't really introduce new inherited attributes over host syntax all that often.  In the worst case with ordinary inherited attributes in Ted's example, Extension 3 would need to redefine the attributes and equations introduced by Extension 1, which would require duplicating a lot of code but isn't a fundamental restriction on what kinds of extensions we can write.
* I actually have been bitten a few times by the "accidental equations" bug, and these are really annoying to debug.  The issue here is that we don't really have a clear way of differentiating which children of a forwarding production we intended to decorate and which ones were only meant to be used as undecorated values, besides the flow analysis by just leaving out the inherited equations.  But when writing or refactoring Silver code, I often use a model of "flow-type-driven-development", by first writing the productions and synthesized equations, then filling in inherited equations as guided by the flow errors.  But this can easily result in equations that shouldn't have been autocopies being missed, or accidentally accessing an attribute and decorating a child with incorrect attributes that shouldn't have decorated in the first place.  
* For these reasons I have gradually come around to Eric's view of "concise but explicit" being better than "implicit" - i.e. one should either have to explicitly provide an equation for an attribute, or explicitly specify at some level that an equation should be generated.  `propagate` syntax for inherited attributes is added in #376; since we have added a global version of propagate that works on all non-forwarding productions of a nonterminal, this isn't a particularly great burden.
