### ISSUE TITLE
this/self-generic attributes

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#287]
Similar to #285 in that "who would need this?" (me and not that badly), it'd be slightly convenient to be able to write something like:

```silver
synthesized attribute elaborated :: this occurs on Decl, Decls, Expr, Signature, ImplicitTys, ImplicitVals, Root;
```

such that

```
decl.elaborated :: Decl
expr.elaborated :: Expr
-- etc.
```

**Comment by tedinski** [comment]
As described, we wouldn't do things this way.

Perhaps I should write up an issue about `functor attributes` though, because those would do exactly what you want. (Their types are what they occur on exactly, and they come with implicit `propogate` for non-forwarding productions.) I'll leave this issue open until I write up that one though.
