### ISSUE TITLE
Origin tracking syntax "overrides"

### ISSUE THREAD

**Issue by 602p** [melt-umn/silver#330]
I've been working on adding origin tracking support to silver. This means enabling silver code to keep track of metadata on the trees it's computing, and to accomplish this I need to add additional behavior to a number of common operations in silver sources:

 - Tree construction / production invocation needs to set a blessed annotation. That is, `foo(bar, baz)` needs to turn into `foo(bar, baz, origininfo=<some logic>)` where `foo` is a production of a nonterminal that tracks it's origins
 - Attribute accesses need to do logic on the resultant values. That is, `foo.bar` needs to turn into `builtin:accesshelper(foo.bar, <some logic>)`
 - `new` calls need a different, deeply-copying implementation. That is, `new(foo)` needs to turn into `builtin:newhelper(foo, <some logic>)`
 - `nonterminal` declarations need to also introduce matching wrapper productions in a certain blessed wrapper nonterminal. That is, `nonterminal Foo` needs to also introduce `abstract production wrapperFoo top::WrapperNT ::= a::Foo {<some logic>}`

Currently, I have the requisite blocks of `<some logic>` implemented, and I have alternate syntax constructs that produce these "instrumented" pieces of code. That is, in origins-using code one writes `foo^.bar` and `foo^(bar, baz)` etc. **The question is: how do we move origin-tracking support into the language in a more effective way than this?**

The current situation (`^.`, `^(`, etc) is not ideal for a number of reasons:

 - It means that a codebase that wants to *start* using origin tracking needs a massive, cross-cutting refactoring. Similarly, a codebase that *might* want to build using origin tracking needs to use these alternate forms *all the time*. (This is an important design consideration Prof. Van Wyk has pointed out: origin tracking should be enable/disable-able, and client code should pay a minimal price when it is disabled.)
 - It means that orthogonal extensions to silver might introduce constructs that forward to the non-origins-aware versions of these constructs, thereby breaking origin tracking in subtle ways. A practical example is that the convenience extension has syntax constructs for declaring nonterminals that forward to the productions from the host language and therefore don't result in the creation of wrapper nonterminals.
 - Additional cognitive load on developers: when do I need to use `.` and when `^.`?

@ericvanwyk and I talked at length today about possible solutions to this issue, and he suggested I write up what we talked about to solicit suggestions:

A major consideration is the wish for it to be easy to *start* using origin tracking in an existing silver codebase, and the wish for it to be easy to "do a build without origin tracking" for a silver codebase. Two possible approaches for this are:

 - Always building the silver compiler with origin tracking support, and having a flag to enable/disable it for the code it is compiling. In this case, one compiler binary could be used to build a origin-tracking or non-origin-tracking version of a silver project based on some `--origins=x` flag.
 - Control the silver compiler's origin-tracking behavior by whether or not the origins grammar is included in the composition. In this case, building a origin-tracking vs non-origin-tracking version of a silver project would be the difference between invoking `silver` and `silver-with-origins` in the build scripts.

Approaches in the latter family (having the origins grammar be conditionally included, and somehow override the host's grammar for these productions) might look like one of the following:

 - Have the origin tracking extension grammar intentionally include a reduce/reduce conflict with the host on these productions, and specify a higher `precedence` value for them. This doesn't actually seem to work in the current version of silver/copper, but is conceptually the most elegant (imo.) This also doesn't solve the problem of orthogonal extensions: something like the convenience extension would still forward to the production from the host language and therefore not get the needed logic for origin tracking.
 - Have the origin tracking extension grammar intentionally include a lexical ambiguity (read: introduce it's own `.` terminal, for example) and win it with a higher `precedence` value/`dominates`/`submits`/disambiguation groups. This does work in current silver, but doesn't solve the orthogonal extension problem: productions forwarding to the host version of `.` would be unaffected.
 - Introduce some form of collection attributes on the host language production that allow arbitrary extension. This seems like it might be the most practical. We'd introduce a collection attribute like `wrappingFunctionsForAccesses` that would collect lambdas to be called on access expressions, where then the result is used for the rest of the compilation. This is relatively practical, but not a great solution general-case. This seems like a serious kludge and introduces extensibility problems like "what if two extensions want to wrap accesses?"
 - Move the "real" logic for accesses/etc to abstract productions, and use some sort of conditional-compilation trickery to choose at compile-time which of the origins-enabled and non-origins-enabled concrete productions to use for the access production. Only one of the "host" and extension productions would be compiled in, and whichever one was would get the `access` production name in the `definition:core` grammar. This means that extensions that forward to `access` would correctly result in origins information on the computed values.

When I talked to Prof. Van Wyk, our conclusion was that the real answer is probably for the origin tracking stuff to move into `definition`. As I've been working on the origins stuff, it has already drifted from `extension` to `modification` as a result of the wish to introduce new inherited attributes on `Expr` that control forwarding. Even as a `modification`, it's still not really playing by the rules:

 - This work has necessitated the addition of new methods to the `Node` class, and their specialization for productions of origins-aware nonterminals. This currently just resides in the `translation:java:core` grammar, since there isn't any way to extend the code we emit for productions (we certainly could add one, but it might not be the best idea to allow extensions to stick arbitrary text into the generated java.)
 - To enable the above, the `Node` class in the runtime has had a few methods added to it's interface.

If it were to be moved into `definition` we'd do something along the lines of the alternative presented above, and have the one true `access` production dispatch to `realAccess`, possibly including additional logic for origin tracking or not based on some compile flag. This seemed like the best solution at the time, as it also means that having code in `translation:java:core` for supporting origin tracking becomes a nonissue.

Before I move ahead with this, I'd like to hear any suggestions that @tedinski or @krame505 for what the best way to move origin tracking into the primetime is.

**Comment by krame505** [comment]
First off, this definitely isn't practical as an extension to Silver, as you surmised.  As to it being a "modification"... well, there never really were rules for what makes something a modification, we just factored the grammar that way a long time ago before we knew what we were doing because it seemed like a good idea.  Such a wide-sweeping change probably needs to go in the core compiler, as you suggested.  

I also agree that concrete-syntax approaches aren't appropriate here, for the reasons you discussed.  For future reference if someone really *did* want to do this as an extension using concrete syntax, the best approach would probably be disambiguation classes that I invented last year for allowing marking terminals that are lexically ambiguous with host terminals.  But there's a bunch of other reasons why that's not a good idea here.  

I also think we should stay away from any approaches that involve using collection attributes and building multiple versions of the Silver compiler.  Testing everything against multiple compiler builds quickly gets annoying, and we already have a seperate version of Silver for writing ableC extensions, so this would just make everything twice as bad.  

The fourth option that you outlined is a fairly reasonable approach at a high level.  Although I do hope you come up with better names than `access` and `realAccess` :-)  This does seem like a ton of work though, and I worry about potential impacts on regular Silver build times.

A much different option could be to instead use the reflection library to perform an optional rewriting transformation across the Silver AST that introduces these extra annotations/wrappers where appropriate.  This could be the least invasive approach, but since you would want to perform error checking on the transformed trees my concern would be to ensure that error messages remain readable.  But if all you are doing for the most part is adding extra annotations on production calls then maybe that is reasonable.  

Finally I'm not sure I entirely understand the "big picture" here.  How would we expect this feature to actually be used?  I am somewhat skeptical of the idea to maintain projects that build in both modes.  Careful thought should also be given to how this works with reflection, as an extra annotation showing up only sometimes would break lots of things.  

For this reason and others I'm not convinced that `origininfo` should actually be an annotation (is it ever specially provided by the user?) and not some independent feature that is baked into the compiler on a deeper level.  Doing this may alleviate some of the issues that arise when trying to express everything in terms of another valid Silver AST - for example having a new version of `access` could be avoided, instead keeping everything to the translation, perhaps involving a new concrete subclass of `Node` in the runtime that takes the place of the generated wrapper productions you found to be needed.  Taking this approach to avoid generating new productions might also avoid many headaches with other Silver extensions such pattern matching.  

Anyway I'm tired so I'll stop rambling now.  Let me know what you think about the above or if you have any further questions.

**Comment by ericvanwyk** [comment]
It does seem that at least parts of this go in the core definition.  If ``origininfo`` is an annotation or not I'm not sure about - but if doing it as an annotation means less messing with Java code then that seems like a good thing.

It does seem unlikely, now reading your comment @krame505, that we would want to run this in two modes - origin tracking on or off - for the same project.  Once a project decides to do origin tracking then it will need to use some version of Silver that has it.  We already have this situation with silver-ableC - once ableC extension decide to use it then it must always use it.

As to using it, it would allow us, if nothing else, to get rid of the explicit setting of the``location`` annotation in ableC.  This would be very nice and it a big reason for adopting origin tracking.

So I'm in favor of having Louis push ahead moving this hooks to his ``<some logic>`` bits into the core definition of Silver.

(As an aside - do we have any other annotations besides ``location``?  This one is defined in a Silver library and used in ableC, but I don't see any other annotations defined anywhere.)

**Comment by ericvanwyk** [comment]
(Also, I'm going camping tomorrow so won't be reading this until the weekend.)

**Comment by krame505** [comment]
> It does seem unlikely, now reading your comment @krame505, that we would want to run this in two modes - origin tracking on or off - for the same project. Once a project decides to do origin tracking then it will need to use some version of Silver that has it. We already have this situation with silver-ableC - once ableC extension decide to use it then it must always use it.

And the main reason for having silver-ableC be seperate from silver is that we don't want silver itself to depend on ableC - which isn't an issue here.  

> As to using it, it would allow us, if nothing else, to get rid of the explicit setting of the location annotation in ableC. This would be very nice and it a big reason for adopting origin tracking.

Is there anywhere that I can read more about what exactly origin tracking is?  Until now I had a vague idea that it has something to do with visualizing program flow graphs.  

> (As an aside - do we have any other annotations besides location? This one is defined in a Silver library and used in ableC, but I don't see any other annotations defined anywhere.)

Not outside of Silver unit test cases.  Although `qualifiers` on `Type` in ableC could probably be made an annotation, which could be interesting to try.

**Comment by ericvanwyk** [comment]
Here is the link to the origin tracking paper:

https://www-users.cs.umn.edu/~evw/pubs/williams14sle/index.html

**Comment by 602p** [comment]
This is long since moot since origin tracking got implemented in core.
