### ISSUE TITLE
Shortening `abstract production` to `production`

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#372]
Eric proposed allowing `production` as a convenience shorthand for `abstract production`.  I think this is a reasonable idea, as we have already used this notation in some papers/theses.  

What are people's thoughts on this?

**Comment by ericvanwyk** [comment]
We should keep ``abstract production`` for backward compatibility reasons.  It might also be a preferred, or at least reasonable, way to write things.  Since Silver is **really** about attribute grammars, then defaulting to abstract seems reasonable.  We've started using the nicer ``concrete productions`` (note the plural) syntax for parser specification anyway.  But curious to hear what other think.

**Comment by RandomActsOfGrammar** [comment]
I think that's a reasonable change to make.  I agree that abstract productions are in some sense the default production type.
