### ISSUE TITLE
Locals with same name in aspect have duplicate equation errors

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#52]
If in grammar a you have a production with a local and inherited equation:

```
abstract production foo
e::Expr ::=
{
  local bar::Expr = ...;
  bar.env = emptyEnv();
}
```

and an aspect with the same local and equation in grammar b:

```
aspect production foo
e::Expr ::=
{
  local bar::Expr = ...;
  bar.env = emptyEnv();
}
```

you get a 'duplicate equation' warning on the line `bar.env = emptyEnv();` in both productions.  There should not be errors, as the locals are totally unrelated.

**Comment by tedinski** [comment]
So... this is a general Silver environment bug. I'm not going to tackle it at the moment. Here's a quick diagnosis:

I wrote a stupid test case with production 'a' and two locals 'y' (in separate grammars.) This actually works, but look at the indexes generated for these:

    generated/src/bug/a/Init.java:public static final int y__ON__bug_a = bug.Init.count_local__ON__bug_a++;
    generated/src/bug/Init.java:public static final int y__ON__bug_a = bug.Init.count_local__ON__bug_a++;

Notice how they're exactly the same except that they're in the two different grammars (bug and bug:a). So, Silver is working essentially by accident here. They're correctly treated as two different locals in the runtime and everything because accesses for each go via the index from the correct grammar. But this immediately suggests a problem if we put the aspect in the same grammar:

    [javac] /home/tedinski/repos/silver/generated/src/bug/Init.java:63: error: variable y__ON__bug_a is already defined in class Init
    [javac] public static final int y__ON__bug_a = bug.Init.count_local__ON__bug_a++;

Silver is trying to use the same translated name for each of them and so boom, java compile error. No Silver error.

## Solution

Silver's environment uses `fName::String` routinely. These take 3 different forms currently:

 * full:grammar:path:shortname. This is standard
 * shortnameonly. This is for things like children, which are names never exported from a grammar and exist only in local environments. This is sort of okay. Probably.
 * full:grammar:path:productionshortname:local:shortname. Literally just the string :local: jammed in there between the name of the production and the name of the local. This is what locals are usually given as a name.

We probably ought to upgrade `fName`s from a `String` to a proper datatype in their own right. Then properly solve the problem of coming up with unique names for locals. Possibly by just genInt()ing an integer in there.

(Strictly speaking, we could probably just do the genInt hack with fNames as Strings, but to make this change, I'd have to re-learn how the whole environment works enough to actually do this change anyway. I'd suggest doing the FullName refactoring, and then solving this bug. A good exercise.)

Additional sidenote: only locals need genInt, but there's technically a bug here for production attributes, too. They should be full-named using a triple of the original production name, *the grammar declaring the production attribute*, and then shortname. Another situation that'd be made better by having a FullName type, instead of hacking this into Strings.

**Comment by krame505** [comment]
Just ran into this bug again while working on halide extension stuff - it would be really nice to be able to use the same name for a local in a bunch of similar aspects on the same production.  
If anyone is interested in messing around with Silver internals, this could be a reasonable place to start.

**Comment by ericvanwyk** [comment]
Why don't you tackle this Lucas?

**Comment by 602p** [comment]
This also effects locals in aspect functions. Reproduction:

```
function foo
Integer ::=
{
  local attribute ret :: Integer = 1;
  return ret;
}

aspect function foo
Integer ::=
{
  local attribute ret :: Integer = 2;
}
```
