### ISSUE TITLE
Remove support for autocopy

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#550]
Per Monday's discussion, it might be possible to add a special case in orphaned-equation-checking for propagating inherited attributes, then to remove `autocopy` from Silver altogether.

- [x] Remove `autocopy` usage from Silver
- [x] Remove `autocopy` usage from projects written in Silver
- [x] Add `propagate` special case
- [x] Add docs about the workaround?
- [ ] Remove `autocopy` support from Silver

**Comment by krame505** [comment]
Preserving this explaination from Slack of why autocopy is a blocker for my partial remote decoration (or whatever we should call it) work...

If I have a production of type `Expr ::= e::Expr`, where `e` has an autocopy attribute `env`, and I want to take a reference to `e` of type `PartiallyDecorated Expr with {}`, then to avoid duplicate equations we want to ban any inherited equations on `e`.  However `e` implicitly gets an equation for `env` anyway due to autocopy, and there isn't currently a way to specify that we don't want a particular autocopy equation.
So if the partially decorated reference we took later gets decorated with `env`, we end up with a duplicate equation, and some attributes on `e` might be computed from the wrong `env`.
It might be possible to work around this and disable autocopy equations on children that have had a partially decorated reference taken, but that will just add more complexity.
