### ISSUE TITLE
Syntax highlighting / folding not working on Eclipse 4.6

### ISSUE THREAD

**Issue by TravisCarlson** [melt-umn/silver#90]
- Follow instructions at http://melt.cs.umn.edu/silver/doc/dev/eclipse/getting-started/
- Tested on [feature/ide](https://github.com/melt-umn/silver/tree/feature/ide) branch with both Linux and Mac
- With Eclipse 4.4, the plugin works successfully
- With Eclipse 4.6:
  - the plugin can be installed successfully and Silver errors are detected under the `Problems` tab
  - but syntax highlighting and folding is not functional in the text editor

**Comment by krame505** [comment]
The time may have come to resurrect this issue.  I recently upgraded to Ubuntu 18.04 which has Java 10 as the default, and it turns out that Eclipse 4.4 no longer runs on Java >= 9.  Downgrading to Java 8 works for now, but this is effectively a block to anyone using Java 10+ - or if we want to use Java 10 for any reason.  

I think Ted said at one point that this has something to do with us using an old version of IMP?  What needs to be done to fix that?

**Comment by tedinski** [comment]
No idea, unfortunately. I've forgotten everything involved in this.

We do have an older IMP hosted on our site that we use. We could figure out how to use the newer IMP hosted elsewhere (or build it from github and host the new version on our site). I *assume* this is still in use by e.g. Rascal and so should work.

But that depends on whether old IMP is actually the problem. That was never definitive, afaik.
