### ISSUE TITLE
readlink in Silver fails on non-symlink files

### ISSUE THREAD

**Issue by ericvanwyk** [melt-umn/silver#95]
Currently the support/bin/silver script has the line

```
ME=$(readlink "${BASH_SOURCE}")
```

This seems to work just fine when a build script calls `silver` and this `silver` is in fact a symlink.  However, I am writing a small testing script that calls a typical build script, but for some reason the symlink is getting resolved.  This causes readlink to fail.

It seems that adding a "-f" flag to readlink in the file solves this problem and using Silver in typical fashion still seems to work.

The man page for readlink give the following description of the -f flag

```
      -f, --canonicalize
              canonicalize  by  following  every symlink in every component of
              the given name recursively; all  but  the  last  component  must
              exist
```

Any objection to adding the -f flag?

**Comment by ericvanwyk** [comment]
Also, any reason not to add
```
set -e
```
at the top of this?  This has the script exit on a non-zero return code from any command executed in the script.  This is also useful in simple testing scripts.

**Comment by tedinski** [comment]
Augh. :( Can you clarify how exactly this happens? Directly invoking `SILVER_HOME/support/bin/silver` instead of a `~/bin/silver`?

We'd removed the `-f` option because macs don't support it. And inserting compatibility code to try to detect this was annoyingly complicated. But after looking at stackoverflow for a bit, perhaps it can be simplified!

We could start the script with

```
set -eu
# On a mac, use the gnu versions of coreutils (for readlink -f)
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# Give a good error message on macs without gnu coreutils
[[ $OSTYPE == darwin* ]] && [[ ! -d /usr/local/opt/coreutils/libexec/gnubin ]] && {
  echo "GNU coreutils are required on macs. 'brew install coreutils'
  exit 1
}
```

and this should automatically find the gnu versions of coreutils if you've installed them on a mac without problem. The above is typed out at a guess and untested. Are you willing to get it to work on a mac and pull request it?

**Comment by ericvanwyk** [comment]
OK, I didn't try the "-f" flag on my mac.

Another option is check if ${BASH_SOURCE} is a symlink or a file and only
call readlink if it is a symlink.  I originally tweaked the silver script
to do this, using the -L and -f tests.  I scrapped when I read about the -f
flag.

I'll revise that and see if it works on coldpress and on my mac.  I suspect
that the -L and -f tests are more stable across platforms than readlink is,
but we'll see.

I'll try to do this tonight sometime.

-Eric
